name: makepdf

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1

      - name: Pull docker (paperist/alpine-texlive-ja)
        uses: docker://paperist/alpine-texlive-ja
      
      - name: Set up Python
        uses: actions/setup-python@v1
      
      - name: Install YAML library
        run: pip3 install pyyaml

      - run: mkdir output

      - name: Generate TeX
        run: python3 github-actions/generate_tex.py

      - name: Make PDF
        run: |
          docker run --rm -v "`pwd`":/workdir paperist/alpine-texlive-ja platex github-actions/library.tex
          docker run --rm -v "`pwd`":/workdir paperist/alpine-texlive-ja platex github-actions/library.tex
          docker run --rm -v "`pwd`":/workdir paperist/alpine-texlive-ja dvipdfmx github-actions/library.dvi
      
      - name: Move PDF
        run: mv github-actions/library.pdf output

      - name: Upload PDF
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
